version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/app
    ports:
      - "9000:9000"
    links:
      - mongo

  app_proxy:
    image: nginx:1.23.2
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template:ro
    environment:
      API_HOST: app:9000
    ports:
      - "9090:80"
    links:
      - app

  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"

  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_HOST_ARG: http://localhost:9090
    ports:
      - "80:80"

volumes:
  mongo_data:
